ITA_Final/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls')),
    path('notes/',include('notes.urls')),
    path('wolfram/',include('wolfram.urls')),
    path('weather/',include('weather.urls')),
    path('reminder/',include('reminders.urls')),
    path('todolist/',include('todolist.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('comments/',include('comments.urls',namespace='comments')),
    path('timings/',include('timings.urls')),
    path('fileshare/',include('filesharing.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from .views import (
    LogInView, RemindUsernameView, SignUpView,  LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),


    path('sign-up/', SignUpView.as_view(), name='sign_up'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard',views.dashboard,name='dashboard')
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)
app_name = 'posts'
urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from .models import Activation


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            messages.warning(request,message='Already Logged In Redirecting')
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = 'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up!'))

        return redirect('dashboard')



class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk)).decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully changed your email!'))

        return redirect('accounts:change_email')


class RemindUsernameView(GuestOnlyView, FormView):
    template_name = 'accounts/remind_username.html'
    form_class = RemindUsernameForm

    def form_valid(self, form):
        user = form.user_cache
        send_forgotten_username_email(user.email, user.username)

        messages.success(self.request, _('Your username has been successfully sent to your email.'))

        return redirect('accounts:remind_username')


class ChangePasswordView(BasePasswordChangeView):
    template_name = 'accounts/profile/change_password.html'

    def form_valid(self, form):
        # Change the password
        user = form.save()

        # Re-authentication
        login(self.request, user)

        messages.success(self.request, _('Your password was changed.'))

        return redirect('accounts:change_password')


class RestorePasswordConfirmView(BasePasswordResetConfirmView):
    template_name = 'accounts/restore_password_confirm.html'

    def form_valid(self, form):
        # Change the password
        form.save()

        messages.success(self.request, _('Your password has been set. You may go ahead and log in now.'))

        return redirect('accounts:log_in')


class RestorePasswordDoneView(BasePasswordResetDoneView):
    template_name = 'accounts/restore_password_done.html'


class LogOutView(LoginRequiredMixin, BaseLogoutView):
    template_name = 'accounts/log_out.html'

accounts/templates/accounts/layout/page.html
    {% load static %}
    {% load bootstrap4 %}
    {% load i18n %}
    {% load staticfiles %}

    {% get_current_language as language_code %}

    <!DOCTYPE html>
    <html lang="{{ language_code }}">
    <head>

        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="CRM Application">
        <meta name="author" content="Gauri Baraskar">

        <link rel="icon" href="{% static 'finallogo.png' %}">

        <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
        <title>CRM</title>

        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
        <style>
            .basics{
                padding-left: 15px;
                margin-left: 15px;
                margin-right: 20px;
            }

            des{

                color: #555555;
            }
            .smh{
                padding-top: 10px;
                padding-left: 10px;
            }
            body{
                    background-color: lightgray;
                    font-family: 'Lato',sans-serif;
                    color: black;

                }

    .sidenav {
        height: 100%;
        width: 0;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        transition: 0.5s;
        padding-top: 60px;
    }

    .sidenav a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 20px;
        color: #818181;
        display: block;
        transition: 0.3s;
    }

    .sidenav a:hover {
        color: #f1f1f1;
    }

    .sidenav .closebtn {
        position: absolute;
        top: 0;
        right: 25px;
        font-size: 36px;
        margin-left: 50px;
    }

    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }

        </style>

        <script>
            function openNav() {
        document.getElementById("mySidenav").style.width = "200px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }

    {% if request.user.is_authenticated %}
function polls(){
    $.post('{% url 'notification' %}',function (result) {
        var chem = result[0];
        console.log(chem['nores'])
        if(chem['nores'] == 1) {
            return;
        }
        else {
            document.getElementById("conts").innerText = chem['description'];
            $("#send").click()
        }
    })
}

$(document).ready(function () {
    var myvar = setInterval(polls,15000);
})

        {% endif %}
        </script>

    </head>

    <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

        {% if request.user.is_authenticated %}
        <div id="mySidenav" class="sidenav navbar-brand">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            </br>
        <a href="{% url 'dashboard' %}">{% trans 'Home' %}</a>
        <a href="{% url 'notes' %}">Notes</a>
            <a href="{% url 'todolist' %}">Assignment<br/>Tracker</a>
        <a href="{% url 'remind' %}">Reminders</a>
        <a href="{% url 'wolfram' %}">Wolfram Engine</a>
        <a href="{% url 'timings' %}">Facilites</a>
        <a href="{% url 'upload' %}">File Sharing</a>
        <a href="{% url 'posts:list' %}">Forum</a>
        </div>

            <span style="cursor:pointer;color: white;font-size: 20px" onclick="openNav()">&#9776;</span>
    {% endif %}




    {#    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">#}
    {#        <span class="navbar-toggler-icon"></span>#}
    {#    </button>#}

        <div class="collapse navbar-collapse " id="navbarsExampleDefault">

            <ul class="navbar-nav mr-auto ">
                {% if request.user.is_authenticated %}
                    {# HERE IS THE DROP DOWN#}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log In' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Sign Up' %}</a>
                    </li>
                {% endif %}
            </ul>

         <p style="padding-top: 10px;color: white">
            {% if request.user.is_authenticated %}
             <div class="basics">
                    <ul class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: white">{{ user.first_name }} {{ user.last_name }}
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="smh"><a href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a></li>
              <li class="smh"><a href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a></li>
              <li class="smh"><a href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a></li>
                <li class="smh"><a href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a></li>
            </ul>
          </ul>
                    </div>
             {% endif %}

         </p>
        </div>

    </nav>

    <div class="container-fluid mt-3">

        {% bootstrap_messages %}

        {% block content %}
            No content.
        {% endblock %}

    </div>

    <script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    </body>

<button hidden="hidden" id="send" class="btn btn-default theme pads" data-toggle="modal" data-target="#myModal">Call Modal</button>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><img src="{% static 'img/clock.png' %}" height="60px" width="60px"></h5>
            <p id="conts" style="margin-right: 10px;font-size: 20px; margin-top: 20px"></p>

        </div>
        <div class="modal-body">
            <div class="row">

            <button type="button" style="margin-left: 20px" class="btn btn-danger float-right" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
      </div>

    </div>
  </div>

    </html>