ITA_Final/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls')),
    path('notes/',include('notes.urls')),
    path('wolfram/',include('wolfram.urls')),
    path('weather/',include('weather.urls')),
    path('reminder/',include('reminders.urls')),
    path('todolist/',include('todolist.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('comments/',include('comments.urls',namespace='comments')),
    path('timings/',include('timings.urls')),
    path('fileshare/',include('filesharing.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from .views import (
    LogInView, RemindUsernameView, SignUpView,  LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),


    path('sign-up/', SignUpView.as_view(), name='sign_up'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard',views.dashboard,name='dashboard')
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)
app_name = 'posts'
urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from django.contrib.auth.models import User
from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(User, default=1,on_delete='cascade')
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True)
    height_field = models.IntegerField(default=50)
    width_field = models.IntegerField(default=100)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=True)
    read_time =  models.IntegerField(default=0) 
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)











posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            #"draft",
        ]

posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except:
    pass

from django.db import connection
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect,reverse
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post

from notes.utils import namedtuplefetchall



def post_create(request):
	if not request.user.is_authenticated:
		raise Http404

	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		print(instance.user)
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "forum/post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser or not request.user.is_authenticated:
			raise Http404
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated:
		c_type = form.cleaned_data.get("content_type")
		#content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(reverse('posts:list'))


	comments = getcomments(request.GET.get('query'))
	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form":form,
		"current_user":request.user,
	}
	return render(request, "forum/post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset,
		"title": "All Questions",
		"page_request_var": page_request_var,
		"today": today,
		"check_user":request.user,
	}
	return render(request, "forum/post_list.html", context)





def post_update(request, slug=None):
	if not request.user.is_authenticated:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		#messages.success(request, "Item Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "forum/post_form.html", context)



def post_delete(request, slug=None):
	if not request.user.is_authenticated:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")


def getcomments(id):
    with connection.cursor() as curr:
        curr.execute("SELECT * from comments_comment WHERE object_id=%s",[id])
        results = namedtuplefetchall(curr)

    return results

templates/forum/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}ProductiveNITK Forum{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >


<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
.col-sm-9-h2{
    float:middle;
    text-align:center;
    inline:true;
}
.inner1{
	display: inline-block;
    padding-right:2em;
}
.inner2{
	display: inline-block;
    padding-left:2em;
}
#logo-img{
    width:2%;
}
#all-img{
    width:100%;
    height : 50%;
}
body{
    background-color: lightgray;
}
.taskAdd {
    background-color: purple;
    padding-left: 31px;
}
        .taskAdd:hover {
    background: rebeccapurple;
}
        .but{
            font-family: 'Open Sans', sans-serif;
    background: purple;
    border-radius: 2px;
    border: none;
    outline: none;
    height: 50px;
    font-size: 14px;
    color: #fff;
    cursor: pointer;
    text-transform: uppercase;
    position: relative;
    -webkit-transition: all 0.3s;
    transition: all 0.3s;
    padding-left: 20px;
    padding-right: 15px;
        }
{% block style %}{% endblock style %}
</style>

{% block head_extra %} {% endblock head_extra %}
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="w3-display-topleft w3-container w3-small">




  </div>
<h2 style="text-align:center;">ProductiveNITK Forum</h2>
<hr/>
{% include "forum/messages_display.html" %}
<div class='container'>
    <ol class='breadcrumb'>
        <li><a href='{% url "dashboard" %}'>Home</a></li>
        {% block post_detail_link %}
        {% endblock %}

        {% if not request.user.is_authenticated %}
        <li class='pull-right'><a href='{% url "accounts:sign_upr" %}'>Register</a></li>
        <li class='pull-right'><a href='{% url "accounts:log_in" %}'>Login</a></li>
        {% else %}
        <li class='pull-right'><a href='{% url "accounts:log_out" %}'>Logout</a></li>
        <li class='pull-right'>{{request.user}}</li>
        {% endif %}
    </ol>

{% block content %}{% endblock content %}
</div>



<!-- Latest compiled and minified JavaScript -->
<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
    })
    $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive");
    })

    var contentInput = $("#id_content");
    function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
        })
    }
    setContent(contentInput.val())
    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })
    var titleInput = $("#id_title");

    function setTitle(value) {
        $("#preview-title").text(value)
    }
    setTitle(titleInput.val())
    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })
    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
    // preview-title
    // preview-content
})
</script>

</body>
</html>

templates/forum/comment_thread.html
{% extends "forum/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{{ object }}



<div class='col-sm-6 col-sm-offset-3'>

        
          <p>{{ comment.content }}</p>
          <footer>Answerd By {{ comment.user }} -- {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %} {% if request.user == comment.user %}<a href='{{ comment.get_delete_url }}'> | Delete</a> {% endif %}</footer>
          <hr/>
          <div>
              {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>Answerd By {{ child_comment.user }} -- {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'> Delete</a>{% endif %}</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Comment' class='btn btn-default'>
            </form>
            {% else %}
            <p>You must login to comment </p>
            {% endif %}
        </div>

    

        <hr/>
</div>


{% endblock content %}

templates/forum/confirm_delete.html
{% extends "forum/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
  <h1>Confirm Delete</h1>
        
      
            <form method="POST" action="."> {% csrf_token %}
                <p>A re you sure you want to delete: "{{ object.content }}"?</p>
              
                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
        </div>

    

        <hr/>
</div>


{% endblock content %}

templates/forum/form.html
{% extends "forum/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

templates/forum/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/forum/post_detail.html
{% extends "forum/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


 {% block post_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
  {% endblock %}


{% block content %}
<div class='col-sm-9 col-sm-offset-0.1'>
        <h1 style="font-size: 30px;color: black;">{{ title }}</h1>
            
         
        <hr/>
{#        <h3 style="color:chocolate;">Question Description:</h3>#}
    {% if instance.image %}
    <img id ="all-img" style="width: 100%;" src='{{ instance.image.url }}' class='img-responsive' />
    {% endif %}

<!-- {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% else %}{{ instance.read_time|time:"i" }} minutes {% endif %} -->



<div class='row'>
<div class='col-sm-12 '>

   <div class='post-detail-item'><p style="color:cornflowerblue ;font-size:25px; font-family: 'Lato', Times, serif;">{{ instance.get_markdown }}</p></div>

    <hr/>
    {% if instance.user %}
<p style="font-size: 15px">Asked By @{{ instance.user }} </p>  <p>{{ instance.publish }}</p>
{% endif %}
{% if instance.user == current_user or instance.user.is_authenticated == current_user %}
                <div class='col-sm-9-h2' style="margin-left: -450px">
        <form class='inner1' action="edit/" method="get">
		    <button class='taskAdd but' type='submit'><i class="fa fa-pencil" style="margin-right: 10px"></i>Edit Question</button>
            
		</form>
        <form class='inner2' action="delete/" method="get">
		    <button class='taskAdd but' type='submit'><i class="fa fa-trash" style="margin-right: 10px"></i>Delete Post</button>
            
		</form>
    </div>
{% endif %}
<hr/>
    <br/>

    <div>


        
        {% if comments %}
        <p class='lead' style="color:chocolate;">All Answers</p>
        {% endif %}
        {% for comment in comments %}

            
        <blockquote>
          <p style="color:cornflowerblue ;">{{ comment.content }}</p>
          <footer>Answered By {{ comment.user }} -- {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a class='comment-reply-btn' href='#'>Comment</a> | <a class='' href='{{ comment.get_absolute_url }}'>View All Replies To This Comment</a></footer>
          <div class='comment-reply'>
              {% for child_comment in comment.children %}
                <blockquote>
                <p style="color:cornflowerblue ;">{{ child_comment.content }}</p>
                <footer>Answered By {{ child_comment.user }} -- {{ child_comment.timestamp|timesince }} ago</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ comment_form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Add Comment' class='btn btn-default'>
            </form>
            {% else %}
        <p>You must login to answer </p>
        {% endif %}
        </div>

        </blockquote>

        <hr/>
        {% endfor %}

        <h3 style="color:black;">Post Your Answer</h3>

        {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
            {{ comment_form|crispy }}<br/>
            <button type='submit' value='Post Answer' class='taskAdd but'><i class="fa fa-bullhorn" style="margin-right: 10px"></i> Post Answer</button>
        </form>
        {% else %}
        <p>You must login to answer </p>
        {% endif %}
        <hr/>
    </div>




</div>
</div>
</div>


{% endblock content %}

templates/forum/post_form.html

{% extends "forum/base.html" %}


{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}
{% load crispy_forms_tags %}
    <head>
    <style>
        body{
            background-color: lightgray;
        }
    </style>
    </head>
<div class='col-sm-6'>
<h3>Preview</h3>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h3>Ask Question</h3>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{#    {{ form.title|as_crispy_field }}<br/>#}
{#    {{ form.content|as_crispy_field }}<br/>#}
{#    {{ form.image|as_crispy_field }}<br/>#}
{#    {{ form.publish|as_crispy_field }}<br/>#}
    {{ form|crispy }}<br/>

    <button type='submit' class='taskAdd but' value='Post Question'><i class="fa fa-question-circle" style="margin-right: 10px"></i> Post Question</button>
</form>
</div>
{% endblock content %}

templates/forum/post_list.html
{% extends "forum/base.html" %}

{% block content %}
    <style>
    .btn{
        background-color: #333333;
        color: white;
        font-size: 20px;
    }
    .btn:hover {
    background-color: purple;


}
    .conts{
        margin-left: auto;
        margin-right: auto;
    }
    .wow1{
        background-color: ghostwhite;
        opacity: 0.8;
        color: black;
    }
    .ol1{
        justify-content: space-between;
    }
    .clean-slide {
    position: relative;
    display: inline-block;
    width: 215px;
    padding: 10px 0 10px 15px;
    font-family: "Open Sans", sans;
    font-weight: 400;
    color: #377D6A;
    background: #efefef;
    border: 0;
    border-radius: 3px;
    outline: 0;
    text-indent: 60px;
    transition: all .3s ease-in-out;
}



.taskAdd {
    background-color: purple;
    padding-left: 31px;
}
        .taskAdd:hover {
    background: rebeccapurple;
}
        .but{
            font-family: 'Open Sans', sans-serif;
    background: purple;
    border-radius: 2px;
    border: none;
    outline: none;
    height: 34px;
    font-size: 14px;
    color: #fff;
    cursor: pointer;
    text-transform: uppercase;
    position: relative;
    -webkit-transition: all 0.3s;
    transition: all 0.3s;
    padding-left: 20px;
    padding-right: 15px;
        }

        .but1{
            font-family: 'Open Sans', sans-serif;
    background: purple;
    border-radius: 2px;
    border: none;
    outline: none;
    height: 34px;
    font-size: 14px;
    color: #fff;
    cursor: pointer;
    text-transform: uppercase;
    position: relative;
    -webkit-transition: all 0.3s;
    transition: all 0.3s;
    padding-left: 20px;
    padding-right: 15px;
        }




    .clean-slide:focus,
.clean-slide:active {
  color: #377D6A;
  text-indent: 0;
  background: #fff;
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;

  &::-webkit-input-placeholder {
    color: #aaa;
  }
  + label {
    color: #fff;
    text-shadow: 0 1px 0 rgba(19,74,70,.4);
    transform: translateX(-100%);

    &:after {
      transform: translate(100%);
    }
  }
}

    </style>
{% if check_user.is_authenticated %}

    <div class="biggie">
    <div id = "wrapper" class="row">


    <div class="col-sm-4">
        <form action="create/" method="get">
		    <button class="taskAdd but1" type="submit"><i class="fa fa-question" style="padding-right: 10px;"></i>Ask a question</button>

		</form>
    </div>

    <div class="col-sm-8">
        <form method='GET' action='' class='row' style="margin-left: 350px">
        <div class='col-sm-6'>
            <div class='input-group'>
                <input class='form-control' style="width: 285px" type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                <span class='input-group-btn'>
                    <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                    <button class='taskAdd but' type='submit'>Search <i class="fa fa-search"></i></button>

                </span>

            </div>

        </div>
</form>
    </div>


    </div>
    {% endif %}

<div class='conts'>
{#    <h1 style="color:chocolate;">{{ title }}</h1>#}


{% for obj in object_list %}
<div class="row wow1">
  <div class="col-sm-12">
{#    <div class="thumbnail">#}

      <div class="caption post-detail-item">
        {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
        <h3 style="color:black;"><a href='{{ obj.get_absolute_url }}?query={{ obj.id }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        {% if obj.user %}<p> Posted by @{{ obj.user }}</p>{% endif %}


{#      </div >#}
    </div>
  </div>
</div>

{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

{#        <span class="current">#}
{#            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.#}
{#        </span>#}

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>
    </div>

{% endblock content %}
